# Generated by Django 2.0.1 on 2018-02-01 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('choose', 'CHOOSE'), ('CSE', 'CSE'), ('IT', 'IT'), ('EEE', 'EEE'), ('ECE', 'ECE'), ('MECH', 'MECH'), ('AUTOMOBILE', 'AUTOMOBILE'), ('CIVIL', 'CIVIL')], default='choose', max_length=150)),
                ('year', models.CharField(choices=[('choose', 'CHOOSE'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='choose', max_length=150)),
                ('semester', models.CharField(choices=[('choose', 'CHOOSE'), ('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV'), ('5', 'V'), ('6', 'VI'), ('7', 'VII'), ('8', 'VIII')], default='choose', max_length=150)),
                ('feedback', models.TextField(max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentsFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('choose', 'CHOOSE'), ('CSE', 'CSE'), ('IT', 'IT'), ('EEE', 'EEE'), ('ECE', 'ECE'), ('MECH', 'MECH'), ('AUTOMOBILE', 'AUTOMOBILE'), ('CIVIL', 'CIVIL')], default='choose', max_length=150)),
                ('year', models.CharField(choices=[('choose', 'CHOOSE'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='choose', max_length=150)),
                ('semester', models.CharField(choices=[('choose', 'CHOOSE'), ('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV'), ('5', 'V'), ('6', 'VI'), ('7', 'VII'), ('8', 'VIII')], default='choose', max_length=150)),
                ('staffName', models.CharField(max_length=150)),
                ('feedback', models.TextField(max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
