# Generated by Django 2.0.1 on 2018-02-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyfeedback',
            name='department',
            field=models.CharField(choices=[('CHOOSE', 'CHOOSE'), ('CSE', 'CSE'), ('IT', 'IT'), ('EEE', 'EEE'), ('ECE', 'ECE'), ('EIE', 'EIE'), ('ETE', 'ETE'), ('MECH', 'MECH'), ('AUTOMOBILE', 'AUTOMOBILE'), ('CIVIL', 'CIVIL')], default='choose', max_length=150),
        ),
        migrations.AlterField(
            model_name='studentsfeedback',
            name='department',
            field=models.CharField(choices=[('CHOOSE', 'CHOOSE'), ('CSE', 'CSE'), ('IT', 'IT'), ('EEE', 'EEE'), ('ECE', 'ECE'), ('EIE', 'EIE'), ('ETE', 'ETE'), ('MECH', 'MECH'), ('AUTOMOBILE', 'AUTOMOBILE'), ('CIVIL', 'CIVIL')], default='choose', max_length=150),
        ),
    ]
